name: Drag.Fling
author: jplarson
category: Interface
tags: [ipod, drag, paging]
docs: http://github.com/jplarson/Drag.Fling/blob/master/README.md
demo: http://www.jpl-consulting.com/projects/MooTools/Drag.Fling/Demo/